# Generated by Django 3.2.23 on 2023-12-11 14:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('map', '0002_remove_event_saved'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='saved',
            field=models.ManyToManyField(blank=True, default=False, related_name='saved', to=settings.AUTH_USER_MODEL),
        ),
    ]
