# Generated by Django 3.2.23 on 2023-11-20 12:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('map', '0009_alter_event_saved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='saved',
            field=models.ManyToManyField(blank=True, default=False, related_name='saved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='eventcomment',
            name='hotel_details',
            field=models.TextField(blank=True, max_length=150, null=True),
        ),
    ]
